# Generated by Django 4.2.20 on 2025-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(max_length=200),
        ),
    ]
